project:
  type: book
  output-dir: docs
  
book:
  title: "CASA23_learning_diary"
  author: "Yifan Feng"
  date: "2025/1/16"
  chapters:
    - index.qmd
    - wk1.qmd
    - wk2.qmd
    - wk3.qmd
    - wk4.qmd
    - wk6.qmd
    - wk7.qmd
    - wk8.qmd
    - wk9.qmd    
    
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

