---
title: "Xaringen and Quarto"
---

This week's assignment was to create a Xaringan presentation in which I demonstrated the features and applications of Landsat 8. We used Quarto to create web pages.

## View the Presentation

```{r, echo=FALSE,warning=FALSE, message=FALSE}

xaringanExtra::embed_xaringan(
  url = "https://evanfeng11.github.io/23Xaringan/xaringan_presentation.html",
  ratio = "16:9"
)

```

## Reflection

When I first started using Xaringan and Quarto, it took some time to get used to them. Xaringan, being based on R, can feel a bit complex for those who aren’t familiar with R, but its high level of customization is definitely a highlight. Quarto, on the other hand, is relatively more beginner-friendly with its Markdown-based syntax, but its rich features still require some exploration to fully grasp. Although the initial learning curve felt a bit challenging, I gradually came to appreciate their power, especially the ability to embed code and enable dynamic updates. The process of adapting might take some effort, but the results are absolutely worth it.